version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 32
    groups:
      telemetry:
        applies-to: version-updates
        patterns:
          - "go.opentelemetry.io/*"
      core:
        applies-to: version-updates
        patterns:
          - "github.com/aws/aws-sdk-go-v2*"
          - "github.com/aws/smithy-go"
          - "github.com/stretchr/testify"
